# Copyright (c) 2026 UChicago Argonne LLC, as Operator of Argonne
#     National Laboratory.
# SPDX-License-Identifier: EPICS
# EPICS BASE is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution.
#*************************************************************************

# This is a Makefile fragment, see modules/libcom/src/Makefile.

SRC_DIRS += $(LIBCOM)/yaml

INC += epicsYaml.h
INC += epicsPvaYaml.h

Com_SRCS += epicsYaml.cpp
Com_SRCS += epicsPvaYaml.cpp
